In [50]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [51]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [52]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [53]:
math.log(32, 2)

5.0

In [54]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [55]:
import math as mt
mt.pi

3.141592653589793

In [56]:
from math import *
print(pi, log(32, 2))

3.141592653589793 5.0


In [57]:
from math import *
from numpy import *
print(pi, log(32, 2))

TypeError: return arrays must be of ArrayType

In [59]:
from math import log, pi
from numpy import asarray

In [58]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:])

numpy.random is a <class 'module'>
it contains names such as... ['seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [60]:
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([4, 3, 2, 4, 2, 2, 5, 4, 1, 3])

In [61]:
type(rolls)

numpy.ndarray

In [63]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [62]:
rolls.mean()

3.0

In [64]:
rolls.tolist()

[4, 3, 2, 4, 2, 2, 5, 4, 1, 3]

In [65]:
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [66]:
[3, 4, 1, 2, 2, 1] + 10

TypeError: can only concatenate list (not "int") to list

In [67]:
rolls + 10

array([14, 13, 12, 14, 12, 12, 15, 14, 11, 13])

In [68]:
rolls <= 3

array([False,  True,  True, False,  True,  True, False, False,  True,
        True])

In [69]:
xlist = [[1, 2, 3], [2, 4, 6],]
x = numpy.asarray(xlist)
print("xlist = {}\nx = \n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x = 
[[1 2 3]
 [2 4 6]]


In [74]:
type(x)

numpy.ndarray

In [72]:
x[1, -1]

6

In [71]:
xlist[1, -1]

TypeError: list indices must be integers or slices, not tuple

In [73]:
xlist[1][-1]

6

In [76]:
import tensorflow as tf
a = tf.constant(1)
b = tf.constant(1)
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [78]:
y = [1, 2, 3]
[1, 2, 3].__contains__(y)

False